apiVersion: v1
kind: Service
metadata:
  name: cryptocurrency-portfolio
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    name: cryptocurrency-portfolio